export default [
  {
    id: 16,
    name: 'Длинное пальто из материала под шерсть',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50],
    color: ['#008000'],
    count: 3200,
    coment: [
      'Мое имя - cтершийся Иероглиф,',
      'Мои одежды залатаны ветром,',
      'Что несу я в зажатых ладонях.',
      'Меня не спросят, и я не отвечу.',
      '-',
      'И как перед битвой, решительной битвой,',
      'Стою у каждого перекрестка.',
      'Hа море асфальта я вижу свой берег,',
      'Свою голубую россыпь.',
      '-',
      'Hа все вопросы pассмеюсь я тихо,',
      'Hа все вопросы не будет ответа,',
      'Ведь имя мое - Иероглиф,',
      'Мои одежды залатаны ветром.',
    ],
    img: ['dlinnoe-palto-iz-materiala-pod-sherst-zelenyj-zhenshiny-razmery-40-54-xr458_1_frf1.webp', 'dlinnoe-palto-iz-materiala-pod-sherst-zelenyj-zhenshiny-razmery-40-54-xr458_1_frf2.webp', 'dlinnoe-palto-iz-materiala-pod-sherst-zelenyj-zhenshiny-razmery-40-54-xr458_1_frf5.webp'],
  },
  {
    id: 17,
    name: 'Куртка в байкерском стиле',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#b46b48'],
    count: 2800,
    coment: [
      'Он не входит в число счастливчиков,',
      'И судьбе его вовсе не жаль.',
      'Его фото не прячет в лифчике,',
      'Та, с четвертого этажа.',
      '-',
      'Так бездарно и так размеренно',
      'Бежит время всему не в такт.',
      'Всё потеряно, всё потеряно,',
      'Неужели же это так?',
      '-',
      'И у самого у последнего',
      'Есть желание мечтать и жить,',
      'Снова пряча в ладонях заветное,',
      'Да с дорогой кривой дружить.',
      '-',
      'И распахнуты окна-двери, да,',
      'Да звезда летит высоко.',
      'Всё потеряно, всё потеряно,',
      'Оттого на душе легко.',
      '-',
      'И ветрами всё будет развеяно,',
      'Будет первым среди бродяг.',
      'Всё потеряно, всё потеряно,',
      'Неужели же это так?',
      '-',
      'И распахнуты окна-двери, да,',
      'Да разорваны башмаки.',
      'Всё потеряно, всё потеряно -',
      'Оттого и шаги легки.',
      '-',
      'Он не входит в число счастливчиков,',
      'И судьбе его вовсе не жаль.',
      'Его фото не прячет в лифчике,',
      'Та, с четвертого этажа.',
      '-',
      'И распахнуты окна-двери, да,',
      'Да звезда летит высоко.',
      'Всё потеряно, всё потеряно,',
      'Оттого на душе легко.',
    ],
    img: ['kurtka-v-bajkerskom-stile-korichnevyj-bolshie-razmery-xo564_4_frf1.webp', 'kurtka-v-bajkerskom-stile-korichnevyj-bolshie-razmery-xo564_4_frf4.webp', 'kurtka-v-bajkerskom-stile-korichnevyj-bolshie-razmery-xo564_4_frf2.webp'],
  },
  {
    id: 18,
    name: 'Длинный пуховик из водоотталкивающего материала',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['black'],
    count: 4300,
    coment: [
      'Это только начало игры,',
      'Будто вниз головой летишь.',
      'Потому будь внимательнее,',
      'Выбирая себе фетиш.',
      '-',
      'Это может быть легкий браслет',
      'И высокие каблуки',
      'Или тонкой резьбы корсет',
      'И перчатка с ее руки.',
      '-',
      'Как дурманящий душу яд,',
      'Как на свежую рану йод.',
      'То сокровище для меня,',
      'Что когда-то касалось ее.',
      '-',
      'И смотрю тебе долго вслед,',
      'Мысли крутятся у виска.',
      'Заговариваю браслет',
      'И дрожит у тебя рука.',
      'Долго-долго еще потом',
      'Раскаленным словам не остыть,',
      'В темной комнате на стене',
      'Проступают твои черты.',
      '-',
      'Как у острого на острие',
      'Будто вниз головой летишь,',
      'Потому будь внимательнее',
      'Выбирая себе фетиш.',
    ],
    img: ['dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf1.webp', 'dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf5.webp', 'dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf2.webp', 'dlinnyj-pukhovik-iz-vodoottalkivayushego-materiala-chernyj-bolshie-razmery-xr616_1_frf3.webp'],
  },
  {
    id: 19,
    name: 'Куртка-сафари',
    category: 'jacket',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#806b2a'],
    count: 2300,
    coment: [
      'Душа самурая - меч,',
      'Душа самурая - меч.',
      '-',
      'За окном сотворение мира для двух мотыльков.',
      'Им хватает еще пыльцы на цветах, что притихли в саду.',
      'А тебе?',
      'Нужна ли пыльца тебе, чтобы также отчаянно жить,',
      'И погибнуть у всех на виду?',
      '-',
      'Душа самурая - меч,',
      'Душа самурая - меч,',
      'Душа самурая - меч,',
      'Душа самурая - меч.',
      '-',
      'Фальшивит ли скрипка, грязны ли слова -',
      'Не слышишь, мечтаешь о чем-то и ждешь…',
      'А ты ведь не Маленький принц, не Джинн, не Али-Баба,',
      'И ярость твоя не разрушит скалу и не вызовет дождь.',
      '-',
      'Душа самурая - меч,',
      'Душа самурая - меч,',
      'Душа самурая - меч,',
      'Душа самурая - меч.',
      '-',
      'И ночь со всеми расплатится тьмой,',
      'А деревья на цыпочки встанут, приблизив себя к небесам,',
      'И город усталый от вечерней молитвы дрожит,',
      'И никто не заметит, как сбудутся чудеса.',
      '-',
      'Душа самурая - меч,',
      'Душа самурая - меч,',
      'Душа самурая - меч,',
      'Душа самурая - меч.',
    ],
    img: ['kurtka-safari-khaki-zhenshiny-razmery-40-54-xe236_1_frf1.webp', 'kurtka-safari-khaki-zhenshiny-razmery-40-54-xe236_1_frf2.webp', 'kurtka-safari-khaki-zhenshiny-razmery-40-54-xe236_1_frf3.webp'],
  },
  {
    id: 20,
    name: 'Облегающие джинсы Eco-conception',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#1560bd'],
    count: 800,
    coment: [
      'За первого встречного выйдет сегодня принцесса',
      'Король безутешен, и в каждом он видит врага.',
      'Кто будет тот встречный угрюмый разбойник из леса,',
      'А может бродяга, и жизнь ему недорога.',
      '-',
      'Вокруг нее тьма обреченных,',
      'Холодное солнце над головой.',
      'Не хочет быть она просто девчонкой,',
      'Не просто девчонкой, а черною-черной вдовой.',
      '-',
      'За первого встречного, кем бы сегодня он ни был,',
      'Весь мир заколдован, она — его малая часть,',
      'Так кто же войдет в ее ложе себе на погибель?',
      'Войдет, чтоб навеки пропасть.',
      '-',
      'Вокруг нее тьма обреченных,',
      'Холодное солнце над головой.',
      'Не хочет быть она просто девчонкой,',
      'Не просто девчонкой, а черною-черной вдовой.',
      '-',
      'А завтра свободна, как ветер,',
      'Свободна и ветрена вновь,',
      'И снова, шутя и беспечно,',
      'Смертельную дарит любовь.',
      '-',
      'Вокруг нее тьма обреченных,',
      'Холодное солнце над головой.',
      'Не хочет быть она просто девчонкой,',
      'Не просто девчонкой, а черною-черной,',
      'А черною-черной, да, самою черной вдовой.',
    ],
    img: ['oblegayushie-dzhinsy-eco-conception-dzhinsovyj-zhenshiny-razmery-40-54-tn785_3_frf1.webp', 'oblegayushie-dzhinsy-eco-conception-dzhinsovyj-zhenshiny-razmery-40-54-tn785_3_frf4.webp', 'oblegayushie-dzhinsy-eco-conception-dzhinsovyj-zhenshiny-razmery-40-54-tn785_3_frf5.webp'],
  },
  {
    id: 21,
    name: ' Джинсы с высокой посадкой',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#42aaff'],
    count: 1500,
    coment: [
      'Ты кукла из папье-маше,',
      'Твой мир – безоблачная даль.',
      'В твоей игрушечной душе',
      'Не помещается печаль.',
      '-',
      'Стучат минуты, только ты',
      'Назло всему всё хорошеешь.',
      'Не помещается печаль',
      'В твоей игрушечной душе.',
      '-',
      'Ты вся молчанье и покой -',
      'Не разгадать и не понять.',
      'Раз мы уж встретились с тобой,',
      'Стань утешеньем для меня.',
      '-',
      'Я буду на тебя смотреть,',
      'Не зная, как же быть.',
      'Я буду для тебя гореть',
      'И в полнолуние чудить, чудить.',
      '-',
      'Недостижимая в углу,',
      'Сидишь и смотришь на меня,',
      'Тебе не грустно, что уже',
      'Нет изначального огня.',
      '-',
      'Когда же ангел протрубит',
      'И скажет, что пора уже,',
      'Лишь ты склонишься надо мной',
      'Ты кукла из папье-маше.',
      '-',
      'Ты кукла из папье-маше.',
      'Ты кукла из папье-маше.',
      'Слушать песню',
    ],
    img: ['dzhinsy-s-vysokoj-posadkoj-goluboj-zhenshiny-razmery-40-54-xt765_1_frf1.webp', 'dzhinsy-s-vysokoj-posadkoj-goluboj-zhenshiny-razmery-40-54-xt765_1_frf2.webp', 'dzhinsy-s-vysokoj-posadkoj-goluboj-zhenshiny-razmery-40-54-xt765_1_frf4.webp'],
  },
  {
    id: 22,
    name: 'Джеггинсы с высокой талией',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#002137'],
    count: 800,
    coment: [],
    img: ['dzhegginsy-s-vysokoj-taliej-temno-sinij-zhenshiny-razmery-40-54-te035_3_frf1.webp', 'dzhegginsy-s-vysokoj-taliej-temno-sinij-zhenshiny-razmery-40-54-te035_3_frf2.webp', 'dzhegginsy-s-vysokoj-taliej-temno-sinij-zhenshiny-razmery-40-54-te035_3_frf4.webp'],
  },
  {
    id: 24,
    name: 'Джинсы стандартного кроя',
    category: 'jeans',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#f5f5dc'],
    count: 1700,
    coment: [],
    img: ['dzhinsy-standartnogo-kroya-bezhevyj-zhenshiny-razmery-40-54-xk963_1_frf1.webp', 'dzhinsy-standartnogo-kroya-bezhevyj-zhenshiny-razmery-40-54-xk963_1_frf2.webp', 'dzhinsy-standartnogo-kroya-bezhevyj-zhenshiny-razmery-40-54-xk963_1_frf3.webp'],
  },
  {
    id: 23,
    name: 'Футболка из трикотажа в рубчик',
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['white'],
    count: 990,
    coment: [],
    img: ['futbolka-iz-trikotazha-v-rubchik-snezhno-belyj-zhenshiny-razmery-40-54-xx438_1_frf1.webp', 'futbolka-iz-trikotazha-v-rubchik-snezhno-belyj-zhenshiny-razmery-40-54-xx438_1_frf3.webp', 'futbolka-iz-trikotazha-v-rubchik-snezhno-belyj-zhenshiny-razmery-40-54-xx438_1_frf4.webp'],
  },
  {
    id: 25,
    name: "disney Футболка 'Минни Маус'",
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['white'],
    count: 750,
    coment: [],
    img: ['futbolka-minni-maus-belyj-zhenshiny-razmery-40-54-xs159_12_frf1.webp', 'futbolka-minni-maus-belyj-zhenshiny-razmery-40-54-xs159_12_frf3.webp'],
  },
  {
    id: 26,
    name: 'Тонкий джемпер с кружевными деталями',
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#082567'],
    count: 1100,
    coment: ['1', '34'],
    img: ['tonkij-dzhemper-s-kruzhevnymi-detalyami-sapfir-zhenshiny-razmery-40-54-xn386_2_frf1.webp', 'tonkij-dzhemper-s-kruzhevnymi-detalyami-sapfir-zhenshiny-razmery-40-54-xn386_2_frf3.webp'],
  },
  {
    id: 27,
    name: 'Футболка с присобранной горловиной',
    category: 'undershirt',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['#f5f5dc'],
    count: 990,
    coment: [],
    img: ['futbolka-s-prisobrannoj-gorlovinoj-chernyj-zhenshiny-razmery-40-54-xn377_1_frf1.webp', 'futbolka-s-prisobrannoj-gorlovinoj-chernyj-zhenshiny-razmery-40-54-xn377_1_frf3.webp'],
  },
  {
    id: 28,
    name: 'Бюстгальтер со спинкой-борцовкой',
    category: 'sport',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['black'],
    count: 1100,
    coment: [],
    img: ['byustgalter-so-spinkoj-bortsovkoj-chernyj-zhenskoe-belje-razmery-s-xxl-vt796_2_frf1.webp', 'byustgalter-so-spinkoj-bortsovkoj-chernyj-zhenskoe-belje-razmery-s-xxl-vt796_2_frf2.webp'],
  },
  {
    id: 29,
    name: 'Спортивные шорты из мольтона',
    category: 'sport',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['black'],
    count: 400,
    coment: [],
    img: ['sportivnye-shorty-iz-moltona-chernyj-zhenshiny-razmery-40-54-xf109_2_frf1.webp', 'sportivnye-shorty-iz-moltona-chernyj-zhenshiny-razmery-40-54-xf109_2_frf2.webp'],
  },
  {
    id: 30,
    name: 'Спортивные брюки-капри',
    category: 'sport',
    size: [40, 42, 44, 46, 48, 50, 52],
    color: ['black'],
    count: 650,
    coment: [],
    img: ['sportivnye-bryuki-kapri-chernyj-zhenshiny-razmery-40-54-xd359_1_frf1.webp', 'sportivnye-bryuki-kapri-chernyj-zhenshiny-razmery-40-54-xd359_1_frf3.webp'],
  },
];
